version: '2'
services:
  web:
    build: .
    depends_on:
      - db
    ports: 
      - "80:5443"
    volumes:
      - web-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment: 
      - HOST=db
      - USER=${ODOO_DATABASE_USER}
      - PASSWORD=${ODOO_DATABASE_PASSWORD}
    restart: always
  db:
    image: postgres:10
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=${ODOO_DATABASE_PASSWORD}
      - POSTGRES_USER=${ODOO_DATABASE_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  web-data:
  db-data: