version: '3'
services:
  web:
    image: odoo:16
    depends_on:
      - db
    ports: 
      - "80:5443"
    volumes:
      - ./data/odoo/:/var/lib/odoo
      - ./config:/etc/odoo
      - ./addons:/mnt/extra-addons
    environment: 
      - HOST=db
      - USER=odoo
    env_file:
      - production.env
    restart: always
  db:
    image: postgres:10
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    env_file:
      - production.env
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data/pgdata
    restart: always
volumes:
  web-data:
  db-data: